services:
  client:
    build: client
    container_name: client-dr
    env_file:
      - client/.env
    ports:
      - 8443:8443
    networks:
      - app-network

  server:
    build:
       context: server/nginx/
       dockerfile: Dockerfile
    container_name: server-dr
    env_file:
      - server/.env
    ports:
      - 443:443
    networks:
      - app-network
      - backend-network
    depends_on:
      - server-express

  server-express: 
    build: 
      context: server
      dockerfile: Dockerfile
    container_name: express-dr
    env_file:
    - server/.env
    ports:
      - 3000:443
    networks:
      - backend-network
    depends_on:
      - db-main

  db-main: 
    image: mysql:latest  
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: darken
      MYSQL_ROOT_PASSWORD: 636mAMnAhymLQos/GjIhe+6uRHm5TK68uP4FPLIP4Yo
    container_name: mysql-dr
    networks:
      - backend-network
    restart: always

networks:
  app-network:
    driver: bridge

  backend-network: 
    driver: bridge
    
